import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
data=np.random.normal(loc=0,scale=1,size=1000)
plt.figure(figsize=(10,6))
sns.histplot(data, kde=False)
plt.title('Histogram')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.show()
plt.figure(figsize=(10,6))
sns.kdeplot(data, shade=True)
plt.title('density plot')
plt.xlabel('Value')
plt.ylabel('Density')
plt.show()
plt.figure(figsize=(10,6))
sns.boxplot(data)
plt.title('box plot')
plt.xlabel('Value')
plt.show()
plt.figure(figsize=(10,6))
sns.violinplot(data)
plt.title('violin plot')
plt.xlabel('Value')
plt.show()
plt.figure(figsize=(10,4))
sns.stripplot(data,jitter=True)
plt.title('Dot plot')
plt.xlabel('Value')
plt.show()
